Homework 2
================

Mahitha Jangeti 11/1/25

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

## Problem 1

``` r
polsmonth_df = 
  read_csv("./fivethirtyeight_datasets/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, into = c("year", "month", "day")) %>% 
  mutate(month = month(as.integer(month), label = TRUE, abbr = FALSE),
    year = as.integer(year),) %>% 
  mutate(president = if_else(prez_gop == 1, "gop", "dem")) %>% 
  select(-prez_gop, -prez_dem, -day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
  knitr::kable(head(polsmonth_df, 8))
```

| year | month    | gov_gop | sen_gop | rep_gop | gov_dem | sen_dem | rep_dem | president |
|-----:|:---------|--------:|--------:|--------:|--------:|--------:|--------:|:----------|
| 1947 | January  |      23 |      51 |     253 |      23 |      45 |     198 | dem       |
| 1947 | February |      23 |      51 |     253 |      23 |      45 |     198 | dem       |
| 1947 | March    |      23 |      51 |     253 |      23 |      45 |     198 | dem       |
| 1947 | April    |      23 |      51 |     253 |      23 |      45 |     198 | dem       |
| 1947 | May      |      23 |      51 |     253 |      23 |      45 |     198 | dem       |
| 1947 | June     |      23 |      51 |     253 |      23 |      45 |     198 | dem       |
| 1947 | July     |      23 |      51 |     253 |      23 |      45 |     198 | dem       |
| 1947 | August   |      23 |      51 |     253 |      23 |      45 |     198 | dem       |

**Cleaning snp data**

``` r
snp_df =
  read_csv("./fivethirtyeight_datasets/snp.csv") %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("month", "day", "year")) %>% 
 mutate(
  month = month(as.integer(month), label = TRUE, abbr = FALSE),
  year  = as.integer(year),
  year  = if_else(year > 25, 1900 + year, 2000 + year))%>% 
  select(-day) %>% 
  relocate(year, month)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
  knitr::kable(head(snp_df, 8))
```

| year | month    |   close |
|-----:|:---------|--------:|
| 2015 | July     | 2079.65 |
| 2015 | June     | 2063.11 |
| 2015 | May      | 2107.39 |
| 2015 | April    | 2085.51 |
| 2015 | March    | 2067.89 |
| 2015 | February | 2104.50 |
| 2015 | January  | 1994.99 |
| 2014 | December | 2058.90 |

**Cleaning unemployment data**

``` r
unemployment_df = 
  read_csv("./fivethirtyeight_datasets/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "percentage_unemployment") %>% 
  mutate(    
    year = as.integer(year),
    month = recode(month,
                   jan = "January",
                   feb = "February",
                   mar = "March",
                   apr = "April",
                   may = "May",
                   jun = "June",
                   jul = "July",
                   aug = "August",
                   sep = "September",
                   oct = "October",
                   nov = "November",
                   dec = "December"))
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
  knitr::kable(head(unemployment_df, 8))
```

| year | month    | percentage_unemployment |
|-----:|:---------|------------------------:|
| 1948 | January  |                     3.4 |
| 1948 | February |                     3.8 |
| 1948 | March    |                     4.0 |
| 1948 | April    |                     3.9 |
| 1948 | May      |                     3.5 |
| 1948 | June     |                     3.6 |
| 1948 | July     |                     3.6 |
| 1948 | August   |                     3.9 |

**Merging Datasets**

``` r
final_df =
  left_join(polsmonth_df, snp_df, by = c("year", "month")) %>% 
  left_join(unemployment_df,by = c("year", "month")) %>% 
  relocate(year, month, president, close, percentage_unemployment)
  knitr::kable(head(final_df, 8))
```

| year | month | president | close | percentage_unemployment | gov_gop | sen_gop | rep_gop | gov_dem | sen_dem | rep_dem |
|---:|:---|:---|---:|---:|---:|---:|---:|---:|---:|---:|
| 1947 | January | dem | NA | NA | 23 | 51 | 253 | 23 | 45 | 198 |
| 1947 | February | dem | NA | NA | 23 | 51 | 253 | 23 | 45 | 198 |
| 1947 | March | dem | NA | NA | 23 | 51 | 253 | 23 | 45 | 198 |
| 1947 | April | dem | NA | NA | 23 | 51 | 253 | 23 | 45 | 198 |
| 1947 | May | dem | NA | NA | 23 | 51 | 253 | 23 | 45 | 198 |
| 1947 | June | dem | NA | NA | 23 | 51 | 253 | 23 | 45 | 198 |
| 1947 | July | dem | NA | NA | 23 | 51 | 253 | 23 | 45 | 198 |
| 1947 | August | dem | NA | NA | 23 | 51 | 253 | 23 | 45 | 198 |

## Five Thirty Eight Data Analysis

The polsmonth_df dataset contains information on number of national
politicians who are democratic vs republican. It included variables such
as **gov_gop**, **sen_gop**, and **rep_gop** to indicate number of
republican governers/senators on associated dates and **gov_dem** etc.
to indicate democratice governers/senators on associated date. The
**prez_gop** variable was mutated to represented if the president was
republican through a binary format (later edited).

The snp_df dataset contains observations related to Standard & Poor’s
Stock market index, which is used as a representative measure of the
stock market as a whole. This is indicated by the \*close\*\* closing
values of the S&P stock index on the associated date (month and year).

The unemployment_df dataset contains information on the percentage of
unemployment throughout the different months of the year. This is
indicated by **year** and **month** that was formatted through
`pivot_longer`.

The final_df dataset has a total of 822 rows and 11 columns. It is
merged through the year and month columns of all three datasets. The
range of years goes from 1947 to 2015 and key variables include
**close**, **percentage_unemployment** , **president**, and associated
dates to see politics and its relation to outcomes in unemployment rates
and values of the stock index.

## Problem 2

``` r
trashwheel_df = 
  read_excel("./fivethirtyeight_datasets/trashwheelcollection.xlsx", 
     sheet = "Mr. Trash Wheel",
     range = "A2:N709",
     na = c("NA",".","")) %>% 
  janitor::clean_names() %>% 
  mutate(sports_balls = as.integer(round(sports_balls)),
         year = as.integer(year),
         trash_wheel = "mr.trash wheel")
```

**Read and Clean Professor Trash Wheel and Gwynnda Trash Wheel sheet**

``` r
professor_trashwheel_df =  
  read_excel( "./fivethirtyeight_datasets/trashwheelcollection.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:L134",
    na = c("NA", ".", "")) %>% 
  janitor::clean_names() %>% 
  mutate(
    year = as.integer(year),
    trash_wheel = "professor trash wheel")
  


gwynns_trashwheel_df =  
  read_excel( "./fivethirtyeight_datasets/trashwheelcollection.xlsx",
    sheet = "Gwynns Falls Trash Wheel",
    range = "A2:K351",
    na = c("NA", ".", "")) %>% 
  janitor::clean_names() %>% 
  mutate(
    year = as.integer(year),
    trash_wheel = "gwynns trash wheel")
```

**Combining Datasets**

``` r
combinewheel_df = 
  bind_rows(trashwheel_df, professor_trashwheel_df, gwynns_trashwheel_df) %>%
  janitor::clean_names() %>% 
  relocate(trash_wheel, dumpster) %>% 
  select(trash_wheel:homes_powered)
```

## Mr. Trashwheel Data Analysis

The Mr. Trashwheel dataset includes information on the Mr. Trash Wheel
waster-wheel vessel and the trash it removes from the Inner Harbor. The
professor_trashweel_df, trashwheel_df, and gwynns_trashwheel_df datasets
give info on the litter type by the date collected and has an additional
column added **trash_wheel** indicating which dataset it is from. The
combinewheel_df is a combined product of the three datasets and
indicated the amount of different litter collected, date of collection,
and which location the data is from.

The total weight of trash collected by Professor Trash Wheel is 282.26
tons and the total number of cigarette butts collected by Gwynnda in
June of 2022 is In addition, the total number of cigarette butts
collected by Gwynnda in June 2022 was 1.812^{4} butts.

## Problem 3

``` r
zori_df = 
  read_csv("./zillow_data/zori.csv", na = c("NA", ".", "")) %>% 
  janitor::clean_names() %>% 
  relocate(county_name) %>% 
  select(-state, county = county_name) %>% 
  mutate(county = county %>% 
            str_replace("New York County", "New York") %>% 
            str_replace("Kings County", "Kings") %>%
            str_replace("Queens County", "Queens") %>%
            str_replace("Bronx County", "Bronx") %>%
            str_replace("Richmond County", "Richmond")) %>% 
  rename(zip_code = region_name) %>% 
  pivot_longer(
    x2015_01_31:x2024_08_31,
    names_to = "date",
    values_to = "zillow observed rent index")
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
  knitr::kable(head(zori_df, 8))
```

| county | region_id | size_rank | zip_code | region_type | state_name | city | metro | date | zillow observed rent index |
|:---|---:|---:|---:|:---|:---|:---|:---|:---|---:|
| Queens | 62080 | 4 | 11368 | zip | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | x2015_01_31 | NA |
| Queens | 62080 | 4 | 11368 | zip | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | x2015_02_28 | NA |
| Queens | 62080 | 4 | 11368 | zip | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | x2015_03_31 | NA |
| Queens | 62080 | 4 | 11368 | zip | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | x2015_04_30 | NA |
| Queens | 62080 | 4 | 11368 | zip | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | x2015_05_31 | NA |
| Queens | 62080 | 4 | 11368 | zip | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | x2015_06_30 | NA |
| Queens | 62080 | 4 | 11368 | zip | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | x2015_07_31 | NA |
| Queens | 62080 | 4 | 11368 | zip | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | x2015_08_31 | NA |

``` r
neighborhood_df = 
  read_csv("./zillow_data/zip_codes.csv", na = c("NA", ".", "")) %>% 
  janitor::clean_names() %>% 
  relocate(county, neighborhood)
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
  knitr::kable(head(neighborhood_df, 8))
```

| county | neighborhood | state_fips | county_code | county_fips | zip_code | file_date |
|:---|:---|---:|:---|---:|---:|:---|
| Bronx | High Bridge and Morrisania | 36 | 005 | 36005 | 10451 | 7/25/07 |
| Bronx | High Bridge and Morrisania | 36 | 005 | 36005 | 10452 | 7/25/07 |
| Bronx | Central Bronx | 36 | 005 | 36005 | 10453 | 7/25/07 |
| Bronx | Hunts Point and Mott Haven | 36 | 005 | 36005 | 10454 | 7/25/07 |
| Bronx | Hunts Point and Mott Haven | 36 | 005 | 36005 | 10455 | 7/25/07 |
| Bronx | High Bridge and Morrisania | 36 | 005 | 36005 | 10456 | 7/25/07 |
| Bronx | Central Bronx | 36 | 005 | 36005 | 10457 | 7/25/07 |
| Bronx | Bronx Park and Fordham | 36 | 005 | 36005 | 10458 | 7/25/07 |

**Merging Datasets**

``` r
zillow_df = 
  left_join(zori_df, neighborhood_df, by = c("zip_code", "county"))%>%
  janitor::clean_names() %>% 
  relocate(county, neighborhood, zip_code, zillow_observed_rent_index)
  knitr::kable(head(zillow_df, 8))
```

| county | neighborhood | zip_code | zillow_observed_rent_index | region_id | size_rank | region_type | state_name | city | metro | date | state_fips | county_code | county_fips | file_date |
|:---|:---|---:|---:|---:|---:|:---|:---|:---|:---|:---|---:|:---|---:|:---|
| Queens | West Queens | 11368 | NA | 62080 | 4 | zip | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | x2015_01_31 | 36 | 081 | 36081 | 7/25/07 |
| Queens | West Queens | 11368 | NA | 62080 | 4 | zip | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | x2015_02_28 | 36 | 081 | 36081 | 7/25/07 |
| Queens | West Queens | 11368 | NA | 62080 | 4 | zip | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | x2015_03_31 | 36 | 081 | 36081 | 7/25/07 |
| Queens | West Queens | 11368 | NA | 62080 | 4 | zip | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | x2015_04_30 | 36 | 081 | 36081 | 7/25/07 |
| Queens | West Queens | 11368 | NA | 62080 | 4 | zip | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | x2015_05_31 | 36 | 081 | 36081 | 7/25/07 |
| Queens | West Queens | 11368 | NA | 62080 | 4 | zip | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | x2015_06_30 | 36 | 081 | 36081 | 7/25/07 |
| Queens | West Queens | 11368 | NA | 62080 | 4 | zip | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | x2015_07_31 | 36 | 081 | 36081 | 7/25/07 |
| Queens | West Queens | 11368 | NA | 62080 | 4 | zip | NY | New York | New York-Newark-Jersey City, NY-NJ-PA | x2015_08_31 | 36 | 081 | 36081 | 7/25/07 |

## Zillow Data Analysis

The dataset contains a total of 17284 observations across 15
variables.There are 149 unique ZIP codes represented and 43 unique
neighborhoods. To tidy the data, I began with zori_df and renamed county
names to only include the name without “count” in order to merge
datasets by the variable. Additionally, region_name was renamed to
zip_code to merge. Lastly, I used `pivot_longer` to have ziro and date
on two separate columns. The neighborhood_df didn’t require too much
tidying as I relocated the variables. Lastly, the merged dataset:
zillow_df was merged through **zip_code** and **county** to display zori
based on neighborhood, county, and zipcode.

**Missing zipcodes from Zillow Rental Price dataset**

``` r
missing_zips = 
  anti_join(neighborhood_df, zori_df, by = c("zip_code", "county"))
knitr::kable(head(missing_zips, 10))
```

| county | neighborhood | state_fips | county_code | county_fips | zip_code | file_date |
|:---|:---|---:|:---|---:|---:|:---|
| Bronx | Southeast Bronx | 36 | 005 | 36005 | 10464 | 7/25/07 |
| Bronx | Hunts Point and Mott Haven | 36 | 005 | 36005 | 10474 | 7/25/07 |
| Bronx | Northeast Bronx | 36 | 005 | 36005 | 10475 | 7/25/07 |
| Bronx | NA | 36 | 005 | 36005 | 10499 | 7/25/07 |
| Bronx | NA | 36 | 005 | 36005 | 10550 | 7/25/07 |
| Bronx | NA | 36 | 005 | 36005 | 10704 | 7/25/07 |
| Bronx | NA | 36 | 005 | 36005 | 10705 | 7/25/07 |
| Bronx | NA | 36 | 005 | 36005 | 10803 | 7/25/07 |
| Kings | NA | 36 | 047 | 36047 | 11202 | 7/25/07 |
| Kings | Southern Brooklyn | 36 | 047 | 36047 | 11224 | 7/25/07 |

Some missing zipcodes include 10464, 10474, 10475, 10499, 10550. The
rest can be found from generating missing_zips. There are 174.This may
be the case because some zip codes are correlated with areas that lack
residential housing or that are not being rented by Zillow. They could
also be associated with bigger public buildings such as airports or
industrial zones.

## Comparing Rental Prices in 2021 to 2020

``` r
jan_compare = 
  zillow_df %>%
  filter(date %in% c("x2020_01_31", "x2021_01_31")) %>%
  select(zip_code, county, neighborhood, date, zillow_observed_rent_index) %>% 
  pivot_wider(
    names_from = "date",
    values_from = "zillow_observed_rent_index") %>% 
  mutate(change = x2021_01_31 - x2020_01_31)
```

``` r
top_ten =
  jan_compare %>% 
  select(change, zip_code, county, neighborhood) %>% 
  arrange(change) %>% 
  slice(1:10)
knitr::kable(head(top_ten, 10))
```

|    change | zip_code | county   | neighborhood                  |
|----------:|---------:|:---------|:------------------------------|
| -912.5966 |    10007 | New York | Lower Manhattan               |
| -748.1245 |    10069 | New York | NA                            |
| -714.2550 |    10009 | New York | Lower East Side               |
| -711.7045 |    10016 | New York | Gramercy Park and Murray Hill |
| -710.4499 |    10001 | New York | Chelsea and Clinton           |
| -710.3028 |    10002 | New York | Lower East Side               |
| -705.9608 |    10004 | New York | Lower Manhattan               |
| -697.5853 |    10038 | New York | Lower Manhattan               |
| -686.2218 |    10012 | New York | Greenwich Village and Soho    |
| -684.9304 |    10010 | New York | Gramercy Park and Murray Hill |

The 10 zipcodes with the largest rental price declines between January
2020 and January 2021 are mostly in Manhattan.We see neighborhoods such
as Lower East Side, Soho, Chelsea, Gramercy Park, and etc. The decreases
were significant as they were all higher than \$600 on average. This was
during covid so more people were probably moving back to the suburbs,
where they wouldn’t have to pay so much. They could also be moving to
other boroughs that were cheaper (especially during a time of
unemployment). This may have resulted in declines in rent and demand for
high-cost apartments. On the other hand, boroughs such as Brooklyn or
Bronx may have experienced smaller declines resulting them to not be
apparent in this table.
